### PR TITLE
Return to the top

### PR DESCRIPTION
**Pull request by brunodlz**
This my first contribution to the MacMagazine :)

So, this **pull request** to aims to return to the top of the list when the user touches the logo on the navigationItem.

nov-04-2017 17-39-03

### CODE REVIEW

**Comment by Themakew** [comment]
The Objective-C code will be soon deprecated, so any contribution please submit to the branch Swift-development. 👍

**Comment by brunodlz** [comment]
👍
Just close this pull request, and please update the **README.md**, this is very important for other developers to contribute to the current branch.

**Comment by Themakew** [comment]
I agree about the README.md, but I am just a contributer as you, @kazziosoftware is the manager and he is a little off for a weeks by now. :(

**Comment by Themakew** [comment]
@rfischmann or @kazziosoftware, anyone to help here? There is this and my pull request to review.

**Comment by kazziosoftware** [comment]
Thanks for the feedback. readme will be updated soon.

In my opinion, this PR (Pull Request) has the same functionality as the tap on the status bar (clock) to scrolll to top.

If everyone agrees that this is useful, I'll approve the PR, but I don't think is necessary.
@rfischmann @Themakew agree?

**Comment by kazziosoftware** [comment]
on the iPhone X the feature works exactly the same way: tap on the clock.

**Comment by Themakew** [comment]
@kazziosoftware What I meant is related with the usability, in the iPhone older than the 8 is really easy to access the feature, in the X I think a little hard the user tap on the screen top left, don`t you agree? Anyway, when the code goes to the swift, it will be the tabbar and this feature will be in it.

**Comment by kazziosoftware** [comment]
Just got a message from @rfischmann and he said that iPhone X has the same way of using. You can either tap on the clock (left side) or on the notch (center of the device) and he said that works like a charm.

**Comment by Themakew** [comment]
@kazziosoftware Great, so I think this pull request can be closed. What do you think?

**Comment by brunodlz** [comment]
For me no problem, I'll try contribute for Swift in next time.

**Comment by kazziosoftware** [comment]
@brunodlz thanks so much for the contribution and, please, contribute on the Swift branch.

**Pull request closed without merging**
